# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@domain.com
url: ""
brand_logo: "assets/brand-logo.png"
# See _data/social_sites_db.yml for list of support sites.
# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - tests/
  - package.json
  - package-lock.json
  - scroll-spy-front-page.gemspec
  - README.md
  - LICENSE.txt
include:
  - .nojekyll # https://www.bennadel.com/blog/3181-including-node-modules-and-vendors-folders-in-your-github-pages-site.htm
  - node_modules
fronts:
  # First page is home page. No link is shown for it. These pages must be in _fronts/.
  - home.html
  - services.html
  - about.html
  - contact.html
default_front_titles: True
home_front_title: True
# full_background_image: /assets/full-background-image.jpg
social_link_urls:
  github: https://github.com/sgpinkus
  stack-overflow: https://stackoverflow.com/
designer:
  name: sgpinkus
  url: https://github.io/sgpinkus/
google_analytics_id: UA-88127304-1
